fil = new Array();
fil["0"]= "Chunk2086168889.htm@@@Creating and Viewing Section Cuts@@@Use the Section Cuts tool to view 2D section planes of your model...";
fil["1"]= "cad_reader_acis_r.htm@@@ACIS Reader@@@Metadata generated from the ACIS reader...";
fil["2"]= "cad_reader_catia_r.htm@@@CATIA Reader@@@Metadata generated from the CATIA reader...";
fil["3"]= "cad_reader_creo_r.htm@@@Creo Reader@@@Metadata generated from the Creo reader...";
fil["4"]= "cad_reader_dxf_r.htm@@@DXF Reader@@@The DXF reader does not generate any metadata...";
fil["5"]= "cad_reader_iges_r.htm@@@IGES Reader@@@Metadata generated from the IGES reader...";
fil["6"]= "cad_reader_inspire_r.htm@@@Inspire Reader@@@Metadata generated from the Inspire reader...";
fil["7"]= "cad_reader_intergraph_r.htm@@@Intergraph Reader@@@Metadata generated from the Intergraph reader...";
fil["8"]= "cad_reader_jt_r.htm@@@JT Reader@@@Metadata generated from the JT reader...";
fil["9"]= "cad_reader_parasolid_r.htm@@@Parasolid Reader@@@Metadata generated from the Parasolid reader...";
fil["10"]= "cad_reader_pdgs_r.htm@@@PDGS Reader@@@The PDGS reader does not generate any metadata...";
fil["11"]= "cad_reader_solidworks_r.htm@@@SolidWorks Reader@@@Metadata generated from the SolidWorks reader...";
fil["12"]= "cad_reader_step_r.htm@@@STEP Reader@@@Metadata generated from the STEP reader...";
fil["13"]= "cad_reader_tribon_r.htm@@@Tribon Reader@@@Metadata generated from the Tribon reader...";
fil["14"]= "cad_reader_vdafs_r.htm@@@VDAFS Reader@@@Metadata generated from the VDAFS reader...";
fil["15"]= "circle_t.htm@@@Creating and Editing Circles@@@Use the Circles tool to create circles for geometry construction or edit free circles, and create/toggle filled circles (that is, disk surfaces)...";
fil["16"]= "defeature_t.htm@@@Removing Rounds, Fillets, Cutouts, Holes@@@Use Defeature the tool to remove rounds, fillets, cutouts, and holes from geometry...";
fil["17"]= "edit_elements_t.htm@@@Editing Elements@@@Use the Edit Elements tool to edit 2D elements by splitting, collapsing, and moving elements...";
fil["18"]= "geometry_solid_create_t.htm@@@Creating Solid Geometry@@@Use the Create Cylinder tool to create cylinders...";
fil["19"]= "intellectual_property_rights_notice_hyperworks_r.htm@@@Intellectual Property Rights Notice@@@Copyrights, trademarks, trade secrets, patents and third party software licenses...";
fil["20"]= "line_t.htm@@@Creating and Editing Lines@@@Use the Lines tool to create and edit lines on geometry or in space...";
fil["21"]= "point_extract_t.htm@@@Interpolating Points and Finding Curve Center@@@Use the Extract Points tool to interpolate points from a line, or find the center point of a curve...";
fil["22"]= "point_t.htm@@@Creating and Editing Points@@@Use the Points tool create and edit points on geometry or in space...";
fil["23"]= "split_t.htm@@@Splitting Surface Edges and Surfaces@@@Use the Split tool to create fixed points to split/unsplit surface edges, draw a line to split surfaces, or pick a splitting plane...";
fil["24"]= "stitch_t.htm@@@Stitching Surfaces and Suppressing Edges@@@Use the Stitch tool to stitch and unstitch adjacent or overlapping surfaces, and suppress or unsuppress edges...";
fil["25"]= "surface_mesh_t.htm@@@Creating and Editing 2D Surface Mesh@@@Use the Surface Mesh tool to create a 2D surface mesh, and edit element density, biasing, and mesh style...";
fil["26"]= "surface_t.htm@@@Patching, Extending, and Offsetting Surfaces@@@Use the Surface tool to patch missing surfaces, create patches by extending surfaces, and offset surfaces...";
fil["27"]= "technical_support_hyperworks_r.htm@@@Technical Support@@@Altair provides comprehensive software support via web FAQs, tutorials, training classes, telephone and e-mail...";
fil["28"]= "topics/chapter_heads/file_management_r.htm@@@File Management@@@Learn how to create, open, import, and save models...";
fil["29"]= "topics/chapter_heads/find_search_r.htm@@@Find and Search@@@Quickly search for HyperWorks tools and panels, or find entites in your model...";
fil["30"]= "topics/chapter_heads/geometry_cleanup_r.htm@@@Geometry Cleanup@@@Cleanup problematic areas on geometry...";
fil["31"]= "topics/chapter_heads/geometry_create_r.htm@@@Create Geometry@@@...";
fil["32"]= "topics/chapter_heads/get_started_r.htm@@@Get Started@@@...";
fil["33"]= "topics/chapter_heads/mesh_r.htm@@@Mesh@@@Create and edit 2D surface mesh...";
fil["34"]= "topics/chapter_heads/midsurface_r.htm@@@Midsurface@@@Extract the midsurface of thin solids, and review and edit midsurface plates...";
fil["35"]= "topics/chapter_heads/tutorials_r.htm@@@Tutorials@@@...";
fil["36"]= "topics/chapter_heads/view_controls_r.htm@@@View Controls@@@View controls enable you to control the view and display of your model in the modeling window...";
fil["37"]= "topics/chapter_heads/whats_new_r.htm@@@What&apos;s New@@@...";
fil["38"]= "topics/chapter_heads/workspace_r.htm@@@Workspace@@@Explore the HyperWorks workspace...";
fil["39"]= "topics/file_management/analysis_results_load_t.htm@@@Loading Results@@@Load analysis results in HyperMesh result format\n            (*.res, *.*)...";
fil["40"]= "topics/file_management/fe_export_t.htm@@@Exporting FE Data@@@Export all FE data in your current HyperWorks session...";
fil["41"]= "topics/file_management/file_formats_supported_r.htm@@@Supported File Formats@@@File formats supported by HyperWorks...";
fil["42"]= "topics/file_management/file_import_t.htm@@@Importing Files@@@Import existing files to the current HyperWorks session...";
fil["43"]= "topics/file_management/model_create_t.htm@@@Creating Models@@@Create a new model...";
fil["44"]= "topics/file_management/model_open_t.htm@@@Opening Models@@@Open an existing model...";
fil["45"]= "topics/file_management/model_save_t.htm@@@Saving Models@@@Save all of the data in your current HyperWorks session to a model file...";
fil["46"]= "topics/file_management/screen_capture_save_t.htm@@@Saving Screen Captures@@@Take a screen capture of your model and save it to your working directory...";
fil["47"]= "topics/file_management/script_command_file_run_t.htm@@@Running Command Files and Scripts@@@Execute a command file or script to automate your workflow...";
fil["48"]= "topics/file_management/solver_interface_change_t.htm@@@Changing Solver Interfaces@@@Load a different solver interface in HyperWorks, or convert model files from one solver format to another...";
fil["49"]= "topics/pre_processing/geometry/cad_reader_catia_composite_link_r.htm@@@CATIA Composites Link Reader@@@Use the CATIA Composites Link option to import drape data. This method is separate from the CATIA reader, where drape data is not imported...";
fil["50"]= "topics/pre_processing/geometry/cad_reader_fibersim_r.htm@@@FiberSim Reader@@@Entities supported by the FiberSim HDF5 reader...";
fil["51"]= "topics/pre_processing/geometry/cad_reader_nx_native_r.htm@@@NX Native Reader@@@Metadata generated from the NX Native reader...";
fil["52"]= "topics/pre_processing/geometry/cad_reader_nx_r.htm@@@NX Reader@@@NX file import is available through two different readers: NXOpen native reader and a third-party non-native reader...";
fil["53"]= "topics/pre_processing/geometry/cad_reader_nx_third_party_r.htm@@@NX Third Party Reader@@@Metadata generated from the NX Third Party reader...";
fil["54"]= "topics/pre_processing/geometry/cad_readers_supported_r.htm@@@Supported CAD Readers@@@CAD readers supported by HyperWorks...";
fil["55"]= "topics/pre_processing/geometry/cutout_remove_t.htm@@@Removing Cutouts@@@Use the Remove Cutouts tool to extend surface edges and remove cutouts...";
fil["56"]= "topics/pre_processing/geometry/edge_suppress_t.htm@@@Suppressing Edges@@@Use the Suppress Edges tool to suppress or unsuppress edges individually or by break angle...";
fil["57"]= "topics/pre_processing/geometry/entity_translate_rotate_t.htm@@@Translating and Rotating Entities@@@Use the Move tool to translate and rotate selected entities...";
fil["58"]= "topics/pre_processing/geometry/geometry_auto_cleanup_t.htm@@@Automatically Cleaning Up Geometry@@@Use the Auto Cleanup tool to automatically stitch and suppress edges, remove edge fillets, and fix overlapping and duplicate surfaces to prepare your model for meshing...";
fil["59"]= "topics/pre_processing/geometry/hole_remove_t.htm@@@Removing Holes@@@Use the Remove Holes tool to find and remove surface holes...";
fil["60"]= "topics/pre_processing/geometry/measure_length_angles_t.htm@@@Measuring Length and Angles@@@Use the Measure tool to measure length and angles...";
fil["61"]= "topics/pre_processing/geometry/midsurface_extract_t.htm@@@Extracting Midsurfaces@@@Use the Midsurface tool to extract the midsurface of thin solids...";
fil["62"]= "topics/pre_processing/geometry/midsurface_plate_edit_t.htm@@@Editing Midsurface Plates@@@Use the Edit Plates tool to review and edit midsurface plates...";
fil["63"]= "topics/pre_processing/geometry/midsurface_plate_types_r.htm@@@Plate & Surface Types@@@The different plate and surface types used when editing a midsurface...";
fil["64"]= "topics/pre_processing/geometry/midsurface_thickness_apply_t.htm@@@Applying Thickness to Midsurface@@@Use the Map Thickness tool to apply thickness values to shell elements on midsurfaced geometry...";
fil["65"]= "topics/pre_processing/geometry/round_fillet_remove_t.htm@@@Removing Rounds and Fillets@@@Use the Remove Rounds & Fillets tool to find and remove both round (convex) and fillet (concave) surfaces...";
fil["66"]= "topics/pre_processing/geometry/settings_display_geometry_r.htm@@@Geometry Display Settings@@@Change the visual display of geometry in the modeling window by configuring the geometry display settings...";
fil["67"]= "topics/pre_processing/geometry/surface_edge_split_t.htm@@@Splitting Surface Edges@@@Use the Split surfaces with lines tool to split surface edges...";
fil["68"]= "topics/pre_processing/geometry/surface_imprint_t.htm@@@Imprinting Surfaces@@@Use the Imprint tool to imprint lines onto surfaces, surfaces onto surfaces, or points onto lines or surfaces...";
fil["69"]= "topics/pre_processing/geometry/surface_split_line_t.htm@@@Splitting Surfaces by Drawing Split Lines@@@Use the Split surfaces with lines tool to draw split lines on straight or curved surfaces...";
fil["70"]= "topics/pre_processing/geometry/surface_split_plane_t.htm@@@Splitting Surfaces and Solids with Planes@@@Use the Split with a plane tool to split surfaces or solids with a plane...";
fil["71"]= "topics/pre_processing/geometry/surface_stitch_t.htm@@@Stitching Surfaces@@@Use the Stitch Surfaces tool to stitch or unstitch adjacent and intersecting surfaces...";
fil["72"]= "topics/pre_processing/meshing/2d_element_quality_review_t.htm@@@Reviewing Element Quality@@@Customize the appearance of the Element Quality view, select the criteria that appears in the Criteria legend, and edit the current 2D element criteria...";
fil["73"]= "topics/pre_processing/meshing/mesh_morph_t.htm@@@Morphing Mesh@@@Use the Morph Mesh tool to morph mesh by moving nodes or by mapping nodes to lines, surfaces, elements, or other nodes...";
fil["74"]= "topics/pre_processing/meshing/settings_display_mesh_r.htm@@@Mesh Display Settings@@@Change the display of mesh in the modeling window by configuring the mesh display settings...";
fil["75"]= "topics/preferences/keyboard_shortcuts_mouse_controls_global_r-1.htm@@@Keyboard Shortcuts and Mouse Controls@@@Default keyboard shortcuts and mouse controls...";
fil["76"]= "topics/preferences/keyboard_shortcuts_mouse_controls_global_r.htm@@@Keyboard Shortcuts and Mouse Controls@@@Default keyboard shortcuts and mouse controls...";
fil["77"]= "topics/preferences/keyboard_shortcuts_mouse_controls_tool_defeature_r.htm@@@Keyboard Shortcuts & Mouse Controls@@@To do this Press Select feature Left Mouse Click Deselect feature Shift + Left Mouse Click Exit tool Esc...";
fil["78"]= "topics/preferences/keyboard_shortcuts_mouse_controls_tool_imprint_r.htm@@@Keyboard Shortcuts & Mouse Controls@@@To do this Press Select all lines and/or surfaces Ctrl + A Imprint Middle Mouse Click Switch between lines and surface selection Tab Exit tool Esc...";
fil["79"]= "topics/preferences/keyboard_shortcuts_mouse_controls_tool_split_r.htm@@@Keyboard Shortcuts & Mouse Controls@@@To do this Press Continue from the last line Ctrl + Left Mouse Click Switch between surfaces/solids and plane on the guide bar . Tab Switch the split orientation from normal to tangent before...";
fil["80"]= "topics/preferences/keyboard_shortcuts_mouse_controls_tool_stitch_r.htm@@@Keyboard Shortcuts & Mouse Controls@@@To do this Press Select surface Left Mouse Click Deselect surface Shift + Left Mouse Click Stitch edge Left Mouse Click Unstitch edge Shift + Left Mouse Click Exit tool Esc...";
fil["81"]= "topics/preferences/settings_display_color_r.htm@@@Model Color Settings@@@Change the color mode for geometry and mesh in the modeling window by selecting a color mode...";
fil["82"]= "topics/release_notes/release_notes_hw_14x120_r.htm@@@HyperWorks 14x.120 Release Notes@@@What&apos;s new and changed in HyperWorks 14x.120...";
fil["83"]= "topics/release_notes/release_notes_hw_2017_1x_r.htm@@@HyperWorks 2017x.1 Release Notes@@@What&apos;s new and changed in HyperWorks 2017x.1...";
fil["84"]= "topics/release_notes/release_notes_hw_2017x_r.htm@@@HyperWorks 2017x Release Notes@@@What&apos;s new and changed in HyperWorks 2017x...";
fil["85"]= "topics/user_interface/browser_model_entity_view_change_t.htm@@@Changing the Entity View in the Model Browser@@@Quickly display all entities of a specific type in the Model Browser...";
fil["86"]= "topics/user_interface/browser_model_overview_c.htm@@@Model Browser@@@The Model Browser displays and organizes all of the objects in your model in a tree structure, and enables access to objects that are not currently shown in the modeling window...";
fil["87"]= "topics/user_interface/context_menu_modeling_window_select_options.htm@@@Window Selection Settings@@@Change window selection settings from the modeling window right-click context menu...";
fil["88"]= "topics/user_interface/entity_search_t.htm@@@Finding and Searching for Entities@@@The search bar can be used to find and filter entities in the Model Browser...";
fil["89"]= "topics/user_interface/menubar_overview_r.htm@@@Menu Bar@@@The File, Edit, and View pull-down menus provide access to standard functions such as New, Open, and Save; Undo and Redo; and Cut, Copy, and Paste. This is also where you can access system preferences, the command window, and help...";
fil["90"]= "topics/user_interface/modeling_window_overview_r.htm@@@Modeling Window@@@The modeling window is where your model is displayed...";
fil["91"]= "topics/user_interface/property_editor_overview_c.htm@@@Entity Editor@@@The Entity Editor shows all the properties of a selected object and enables you to edit them...";
fil["92"]= "topics/user_interface/ribbon_r.htm@@@Ribbons@@@The ribbon allows you to quickly access tools and standard functions, and is located along the top of HyperWorks.\n     Click on an icon to open the related tool. Hovering over a group of icons may reveal additional tools...";
fil["93"]= "topics/user_interface/selection_t.htm@@@Selecting Entities@@@Select and deselect entities to modify with other HyperWorks tools. Selected entities are outlined to indicate their selection state...";
fil["94"]= "topics/user_interface/tools_search_t.htm@@@Searching for Tools and Panels@@@Quickly find and access HyperWorks tools and panels...";
fil["95"]= "topics/user_interface/view_show_hide_isolate_t.htm@@@Showing, Hiding, Isolating Entities@@@Turn the display of entities on and off in the modeling window...";
fil["96"]= "view_adjust_t.htm@@@Rotate, Pan, Zoom, Fit, Center@@@Center the view around a selected point...";
fil["97"]= "view_store_recall_t.htm@@@Storing and Recalling Custom Views@@@Recall a saved view...";
